[project]
name = "trinity"
version = "0.0.1"
description = "Retirement calculator based on the Trinity study"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
trinity = "trinity.simulation:main"

[tool.uv.build-backend]
source-include = ["data/*.csv"]
module-root = "."

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.mypy]
files = ["trinity/**/*.py"]
strict = true

[tool.pytest.ini_options]
addopts = "--cov=trinity --cov-report=term-missing"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "pytest-console-scripts>=1.4.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.8",
]
